# Generated by Django 4.2.28 on 2026-03-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='thread_id',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='user_id',
            new_name='user',
        ),
    ]
